import type { Metadata } from "next";

import { fontFamily } from "@/utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "WooPilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${fontFamily.interFont.className}`}
      >
        {/* <main className="grow"></main> */}
        {children}
      </body>
    </html>
  );
}
